#if defined(BUILD_PARALLEL_32_INT)
#define key_schedule_stream ffdecsa_int_key_schedule_stream
#define key_schedule_block ffdecsa_int_key_schedule_block
#define block_decypher_group ffdecsa_int_block_decypher_group
#define get_internal_parallelism ffdecsa_int_get_internal_parallelism
#define get_suggested_cluster_size ffdecsa_int_get_suggested_cluster_size
#define get_key_struct ffdecsa_int_get_key_struct
#define free_key_struct ffdecsa_int_free_key_struct
#define schedule_key ffdecsa_int_schedule_key
#define set_control_words ffdecsa_int_set_control_words
#define set_even_control_word ffdecsa_int_set_even_control_word
#define set_odd_control_word ffdecsa_int_set_odd_control_word
#define get_control_words ffdecsa_int_get_control_words
#define decrypt_packets ffdecsa_int_decrypt_packets
#define stream_cypher_group_init ffdecsa_int_stream_cypher_group_init
#define stream_cypher_group_normal ffdecsa_int_stream_cypher_group_normal
#elif defined(BUILD_PARALLEL_64_MMX)
#define key_schedule_stream ffdecsa_mmx_key_schedule_stream
#define key_schedule_block ffdecsa_mmx_key_schedule_block
#define block_decypher_group ffdecsa_mmx_block_decypher_group
#define get_internal_parallelism ffdecsa_mmx_get_internal_parallelism
#define get_suggested_cluster_size ffdecsa_mmx_get_suggested_cluster_size
#define get_key_struct ffdecsa_mmx_get_key_struct
#define free_key_struct ffdecsa_mmx_free_key_struct
#define schedule_key ffdecsa_mmx_schedule_key
#define set_control_words ffdecsa_mmx_set_control_words
#define set_even_control_word ffdecsa_mmx_set_even_control_word
#define set_odd_control_word ffdecsa_mmx_set_odd_control_word
#define get_control_words ffdecsa_mmx_get_control_words
#define decrypt_packets ffdecsa_mmx_decrypt_packets
#define stream_cypher_group_init ffdecsa_mmx_stream_cypher_group_init
#define stream_cypher_group_normal ffdecsa_mmx_stream_cypher_group_normal
#elif defined(BUILD_PARALLEL_64_LONG)
#define key_schedule_stream ffdecsa_long_key_schedule_stream
#define key_schedule_block ffdecsa_long_key_schedule_block
#define block_decypher_group ffdecsa_long_block_decypher_group
#define get_internal_parallelism ffdecsa_long_get_internal_parallelism
#define get_suggested_cluster_size ffdecsa_long_get_suggested_cluster_size
#define get_key_struct ffdecsa_long_get_key_struct
#define free_key_struct ffdecsa_long_free_key_struct
#define schedule_key ffdecsa_long_schedule_key
#define set_control_words ffdecsa_long_set_control_words
#define set_even_control_word ffdecsa_long_set_even_control_word
#define set_odd_control_word ffdecsa_long_set_odd_control_word
#define get_control_words ffdecsa_long_get_control_words
#define decrypt_packets ffdecsa_long_decrypt_packets
#define stream_cypher_group_init ffdecsa_long_stream_cypher_group_init
#define stream_cypher_group_normal ffdecsa_long_stream_cypher_group_normal
#elif defined(BUILD_PARALLEL_128_SSE2)
#define key_schedule_stream ffdecsa_sse2_key_schedule_stream
#define key_schedule_block ffdecsa_sse2_key_schedule_block
#define block_decypher_group ffdecsa_sse2_block_decypher_group
#define get_internal_parallelism ffdecsa_sse2_get_internal_parallelism
#define get_suggested_cluster_size ffdecsa_sse2_get_suggested_cluster_size
#define get_key_struct ffdecsa_sse2_get_key_struct
#define free_key_struct ffdecsa_sse2_free_key_struct
#define schedule_key ffdecsa_sse2_schedule_key
#define set_control_words ffdecsa_sse2_set_control_words
#define set_even_control_word ffdecsa_sse2_set_even_control_word
#define set_odd_control_word ffdecsa_sse2_set_odd_control_word
#define get_control_words ffdecsa_sse2_get_control_words
#define decrypt_packets ffdecsa_sse2_decrypt_packets
#define stream_cypher_group_init ffdecsa_sse2_stream_cypher_group_init
#define stream_cypher_group_normal ffdecsa_sse2_stream_cypher_group_normal
#else
#error build not defined
#endif

static void block_decypher_group() __attribute__ ((hot));
int decrypt_packets() __attribute__ ((hot));
void stream_cypher_group_init() __attribute__ ((hot));
void stream_cypher_group_normal() __attribute__ ((hot));
